/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LifecycleDemo {}
}

declare global {


  interface HTMLLifecycleDemoElement extends Components.LifecycleDemo, HTMLStencilElement {}
  var HTMLLifecycleDemoElement: {
    prototype: HTMLLifecycleDemoElement;
    new (): HTMLLifecycleDemoElement;
  };
  interface HTMLElementTagNameMap {
    'lifecycle-demo': HTMLLifecycleDemoElement;
  }
}

declare namespace LocalJSX {
  interface LifecycleDemo extends JSXBase.HTMLAttributes<HTMLLifecycleDemoElement> {
    'onButtonClickEvent'?: (event: CustomEvent<any>) => void;
    'onComponentDidLoadEvent'?: (event: CustomEvent<any>) => void;
    'onComponentWillLoadEvent'?: (event: CustomEvent<any>) => void;
    'onComponentWillRenderEvent'?: (event: CustomEvent<any>) => void;
    'onConnectedCallbackEvent'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'lifecycle-demo': LifecycleDemo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


